apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pizza-store-config
  namespace: default
spec:
  features:
    - name: HotReload
      enabled: true
  accessControl:
    defaultAction: deny
    trustDomain: td1
